### ISSUE TITLE
Tagging this release

### ISSUE THREAD

**Issue by pkriens** [sondreb/action-release#10]
This is exactly what I am looking for ... I understand it is not release but could you at least give the current master a tag? I do not feel comfortable using it on master.

Thanks. Surprised that this is not a standard feature on the other release actions.

**Comment by sondreb** [comment]
Thanks for the feedback!

Added an 0.0.1 tag so you can use it without relying on the main branch:

https://github.com/sondreb/action-release/tree/0.0.1
