### ISSUE TITLE
does this re-use a pushed tag?

### ISSUE THREAD

**Issue by nerdCopter** [sondreb/action-release#3]
i'm also a bit frustrated with `actions/create-release@v1`.  
if i `git push tag` will this allow that tag "release" to be modified and converted to draft?

**Comment by sondreb** [comment]
I'm not maintainer of the `actions/create-release@v1`, but this library will update the draft release on every build. You can change the tag on a draft when you publish a release. This action will set the tag on every build, so if you save, it will edit back until you release (then it becomes locked).

**Comment by nerdCopter** [comment]
:) i have learned so much since that question :wink: , but thank you!
