### ISSUE TITLE
Doesn't work with repo's that don't use master

### ISSUE THREAD

**Issue by Trojaner** [sondreb/action-release#8]
We recently renamed master to main and that broke our workflows using this action

https://github.com/sondreb/action-release/blob/8e6be173026b039c2f840b74c6295589b97c65be/action.js#L40

```
Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}
```

**Comment by sondreb** [comment]
Thanks for reporting! This has now been fixed by introducing an "main" release.

Usage:

```
uses: sondreb/action-release@main
```
